apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wy-serve
  name: wy-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wy-serve
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wy-serve
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: mumoshu/wy:latest
        name: wy
        command:
        - wy
        args:
        - serve
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wy-serve
  name: wy-serve
spec:
  ports:
  - name: 8080-8080
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wy-serve
  type: NodePort
status:
  loadBalancer: {}
