apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: wy
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: wy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wy
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
